### ISSUE TITLE
Support Minecraft 1.19

### ISSUE THREAD

**Issue by osfanbuff63** [mcbeet/mecha#152]
This version replaced the `/placefeature` command with `/place <structure | feature | jigsaw> <input> [coords]`, and replaces `/locatebiome` and `/locate` with `/locate <structure | poi | biome> <input>`. Would love it as I'm thinking about changing to use beet with datapack/resourcepack development, and use the `check-commands` GitHub action in my CI :P

**Comment by osfanbuff63** [comment]
Wait no, I put this on the wrong repo :P

**Comment by vberlier** [comment]
@osfanbuff63 The latest releases of `beet/mecha` use 1.19 as default Minecraft version so if you're using the `check-commands` action you should bump the mecha version to update the cached virtualenv.
