### ISSUE TITLE
Relative function paths aren't resolved in `schedule clear` commands

### ISSUE THREAD

**Issue by Arcensoth** [mcbeet/mecha#66]
As the title says, the `schedule clear` command doesn't have its relative functions resolved.

There's `schedule clear` which for whatever reason Mojang decided should use the `brigadier:string` parser and also be `greedy`. I suspect this is the reason for this particular subcommand.

~~I did a brief scan and couldn't figure out why this is happening for the `schedule function` subcommand. It uses the `minecraft:function` parser just like the `function` command does, and the latter works just fine. Could it have something to do with `schedule function` taking additional trailing arguments?~~

Update: `schedule function` works fine and I must have confused something with `schedule clear` in my testing.

**Comment by vberlier** [comment]
Relative resource locations are resolved during parsing by the resource location parser so it looks like `brigadier:string` was indeed the issue. This is fixed in `v0.34.1` thanks to a new system that allows mecha to load patches for the command tree.
